<?php
    include_once ('../../../server/Connect.php');
    $conn = new Conn();

        $ID_ADMINISTRADOR = $_POST['ID_ADMINISTRADOR'];
        $NOME_ADMINISTRADOR = $_POST['NOME_ADMINISTRADOR'];
        $RG_ADMINISTRADOR = $_POST['RG_ADMINISTRADOR'];
        $CPF_ADMINISTRADOR = $_POST['CPF_ADMINISTRADOR'];
        $CELULAR_ADMINISTRADOR = $_POST['CELULAR_ADMINISTRADOR'];
        $CIDADE_ADMINISTRADOR = $_POST['CIDADE_ADMINISTRADOR'];
        $DATA_NASCIMENTO_ADMINISTRADOR = $_POST['DATA_NASCIMENTO_ADMINISTRADOR'];
        $SEXO_ADMINISTRADOR = $_POST['SEXO_ADMINISTRADOR'];
        $EMAIL_ADMINISTRADOR = $_POST['EMAIL_ADMINISTRADOR'];
        $CEP_ADMINISTRADOR = $_POST['CEP_ADMINISTRADOR'];
        $ESTADO_ADMINISTRADOR = $_POST['ESTADO_ADMINISTRADOR'];
        $BAIRRO_ADMINISTRADOR = $_POST['BAIRRO_ADMINISTRADOR'];
        $ENDERECO_ADMINISTRADOR = $_POST['ENDERECO_ADMINISTRADOR'];
        $COMPLEMENTO_ADMINISTRADOR = $_POST['COMPLEMENTO_ADMINISTRADOR'];
        $NACIONALIDADE_ADMINISTRADOR = $_POST['NACIONALIDADE_ADMINISTRADOR'];

        try {
            $sql = "UPDATE administrador SET NOME_ADMINISTRADOR = :NOME_ADMINISTRADOR, RG_ADMINISTRADOR = :RG_ADMINISTRADOR, CPF_ADMINISTRADOR = :CPF_ADMINISTRADOR, CELULAR_ADMINISTRADOR = :CELULAR_ADMINISTRADOR, CIDADE_ADMINISTRADOR = :CIDADE_ADMINISTRADOR,
            DATA_NASCIMENTO_ADMINISTRADOR = :DATA_NASCIMENTO_ADMINISTRADOR, SEXO_ADMINISTRADOR = :SEXO_ADMINISTRADOR, EMAIL_ADMINISTRADOR = :EMAIL_ADMINISTRADOR, CEP_ADMINISTRADOR = :CEP_ADMINISTRADOR, ESTADO_ADMINISTRADOR = :ESTADO_ADMINISTRADOR, BAIRRO_ADMINISTRADOR = :BAIRRO_ADMINISTRADOR, ENDERECO_ADMINISTRADOR = :ENDERECO_ADMINISTRADOR, COMPLEMENTO_ADMINISTRADOR = :COMPLEMENTO_ADMINISTRADOR, NACIONALIDADE_ADMINISTRADOR = :NACIONALIDADE_ADMINISTRADOR  WHERE ID_ADMINISTRADOR = :ID_ADMINISTRADOR";

            $resultado = $conn->getConn()->prepare($sql);
            $resultado->bindParam(':NOME_ADMINISTRADOR', $NOME_ADMINISTRADOR);
            $resultado->bindParam(':RG_ADMINISTRADOR', $RG_ADMINISTRADOR);
            $resultado->bindParam(':CPF_ADMINISTRADOR', $CPF_ADMINISTRADOR);
            $resultado->bindParam(':CELULAR_ADMINISTRADOR', $CELULAR_ADMINISTRADOR);
            $resultado->bindParam(':CIDADE_ADMINISTRADOR', $CIDADE_ADMINISTRADOR);
            $resultado->bindParam(':DATA_NASCIMENTO_ADMINISTRADOR', $DATA_NASCIMENTO_ADMINISTRADOR);
            $resultado->bindParam(':SEXO_ADMINISTRADOR', $SEXO_ADMINISTRADOR);
            $resultado->bindParam(':EMAIL_ADMINISTRADOR', $EMAIL_ADMINISTRADOR);
            $resultado->bindParam(':CEP_ADMINISTRADOR', $CEP_ADMINISTRADOR);
            $resultado->bindParam(':ESTADO_ADMINISTRADOR', $ESTADO_ADMINISTRADOR);
            $resultado->bindParam(':BAIRRO_ADMINISTRADOR', $BAIRRO_ADMINISTRADOR);
            $resultado->bindParam(':ENDERECO_ADMINISTRADOR', $ENDERECO_ADMINISTRADOR);
            $resultado->bindParam(':COMPLEMENTO_ADMINISTRADOR', $COMPLEMENTO_ADMINISTRADOR);
            $resultado->bindParam(':NACIONALIDADE_ADMINISTRADOR', $NACIONALIDADE_ADMINISTRADOR);
            $resultado->bindParam(':ID_ADMINISTRADOR', $ID_ADMINISTRADOR);
            $resultado->execute();
            
            $data = array('return' => true);

        } catch (Exception $ex){
            $data = array('return' => $ex->getMessage());
        }
            echo json_encode($data);
?>
