<?php
    include_once('../../../server/conexao.php');

    $ID_FORNECEDORES = $_POST['ID_FORNECEDORES'];
    $NOME_FANTASIA_FORNECEDORES = $_POST['NOME_FANTASIA_FORNECEDORES'];
    $RAZAO_SOCIAL_FORNECEDORES = $_POST['RAZAO_SOCIAL_FORNECEDORES'];
    $CNPJ_FORNECEDORES = $_POST['CNPJ_FORNECEDORES'];
    $EMAIL_FORNECEDORES = $_POST['EMAIL_FORNECEDORES'];
    $CELULAR_FORNECEDORES = $_POST['CELULAR_FORNECEDORES'];
    $SEXO_FORNECEDORES = $_POST['SEXO_FORNECEDORES'];
    $DATA_NASCIMENTO_FORNECEDORES = $_POST['DATA_NASCIMENTO_FORNECEDORES'];
    $NACIONALIDADE_FORNECEDORES = $_POST['NACIONALIDADE_FORNECEDORES'];
    $CEP_FORNECEDORES = $_POST['CEP_FORNECEDORES'];
    $CIDADE_FORNECEDORES = $_POST['CIDADE_FORNECEDORES'];
    $ENDERECO_FORNECEDORES = $_POST['ENDERECO_FORNECEDORES'];
    $ESTADO_FORNECEDORES = $_POST['ESTADO_FORNECEDORES'];
    $NUMERO_FORNECEDORES = $_POST['NUMERO_FORNECEDORES'];
    $BAIRRO_FORNECEDORES = $_POST['BAIRRO_FORNECEDORES'];
    $COMPLEMENTO_FORNECEDORES = $_POST['COMPLEMENTO_FORNECEDORES'];



        $sql = "UPDATE fornecedores
                    SET NOME_FANTASIA_FORNECEDORES = '".$NOME_FANTASIA_FORNECEDORES."',
                        RAZAO_SOCIAL_FORNECEDORES = '".$RAZAO_SOCIAL_FORNECEDORES."',
                        CNPJ_FORNECEDORES = '".$CNPJ_FORNECEDORES."',
                        EMAIL_FORNECEDORES = '".$EMAIL_FORNECEDORES."',
                        CELULAR_FORNECEDORES = '".$CELULAR_FORNECEDORES."',
                        SEXO_FORNECEDORES = '".$SEXO_FORNECEDORES."',
                        DATA_NASCIMENTO_FORNECEDORES = '".$DATA_NASCIMENTO_FORNECEDORES."',
                        NACIONALIDADE_FORNECEDORES = '".$NACIONALIDADE_FORNECEDORES."',
                        CEP_FORNECEDORES = '".$CEP_FORNECEDORES."',
                        CIDADE_FORNECEDORES = '".$CIDADE_FORNECEDORES."',
                        ENDERECO_FORNECEDORES = '".$ENDERECO_FORNECEDORES."',
                        ESTADO_FORNECEDORES = '".$ESTADO_FORNECEDORES."',
                        NUMERO_FORNECEDORES = '".$NUMERO_FORNECEDORES."',
                        BAIRRO_FORNECEDORES = '".$BAIRRO_FORNECEDORES."',
                        COMPLEMENTO_FORNECEDORES = '".$COMPLEMENTO_FORNECEDORES."',
                        WHERE ID_FORNECEDORES = '".$ID_FORNECEDORES."'
                ";

        if (mysqli_query($conn, $sql)) {
            $data = array("return" => true);
        } else {
            $data = array("return" => mysqli_error($conn));
        }

    echo json_encode($data);

?>
